const AMOGUS_PATTERN = [
  { x: 1, y: 0, color: null },
  { x: 2, y: 0, color: null },
  { x: 0, y: 1, color: null },
  { x: 0, y: 2, color: null },
  { x: 1, y: 2, color: null },
  { x: 2, y: 2, color: null },
  { x: 1, y: 3, color: null },
  { x: 2, y: 3, color: null },
  { x: 0, y: 3, color: null },
  { x: 0, y: 4, color: null },
  { x: 2, y: 4, color: null },
  { x: -1, y: 1, color: null },
  { x: -1, y: 2, color: null },
];

const REVERSED_AMOGUS_PATTERN = [
  { x: -1, y: 0, color: null },
  { x: -2, y: 0, color: null },
  { x: -0, y: 1, color: null },
  { x: -0, y: 2, color: null },
  { x: -1, y: 2, color: null },
  { x: -2, y: 2, color: null },
  { x: -1, y: 3, color: null },
  { x: -2, y: 3, color: null },
  { x: -0, y: 3, color: null },
  { x: -0, y: 4, color: null },
  { x: -2, y: 4, color: null },
  { x: 1, y: 1, color: null },
  { x: 1, y: 2, color: null },
];

const HEART_PATTERN = [
  // right side
  { x: 1, y: -1, color: null },
  { x: 2, y: -2, color: null },
  { x: 3, y: -2, color: null },
  { x: 4, y: -2, color: null },
  { x: 5, y: -1, color: null },
  { x: 6, y: 0, color: null },
  { x: 6, y: 1, color: null },
  { x: 6, y: 2, color: null },
  { x: 5, y: 3, color: null },
  { x: 4, y: 4, color: null },
  { x: 3, y: 5, color: null },
  { x: 2, y: 6, color: null },
  { x: 1, y: 7, color: null },
  { x: 0, y: 8, color: null },
  // left side
  { x: -1, y: -1, color: null },
  { x: -2, y: -2, color: null },
  { x: -3, y: -2, color: null },
  { x: -4, y: -2, color: null },
  { x: -5, y: -1, color: null },
  { x: -6, y: 0, color: null },
  { x: -6, y: 1, color: null },
  { x: -6, y: 2, color: null },
  { x: -5, y: 3, color: null },
  { x: -4, y: 4, color: null },
  { x: -3, y: 5, color: null },
  { x: -2, y: 6, color: null },
  { x: -1, y: 7, color: null },
];
